# Generated by Django 3.0.7 on 2020-06-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobType',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
