# Generated by Django 3.0.7 on 2020-06-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200627_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobType',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelancer', 'Freelancer')], max_length=15),
        ),
    ]
