# Generated by Django 3.0.7 on 2020-06-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20200627_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobType',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelancers', 'Freelancer')], max_length=15),
        ),
    ]
