# Generated by Django 3.0.7 on 2020-06-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20200627_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobType',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('F', 'Freelancer')], max_length=15),
        ),
    ]
