# Generated by Django 3.0.7 on 2020-06-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='publishedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Enter the time'),
        ),
    ]
