# Generated by Django 3.0.7 on 2020-06-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20200627_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='publishedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
